// <auto-generated />
namespace RncManagement.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CambioDataTypeFecha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambioDataTypeFecha));
        
        string IMigrationMetadata.Id
        {
            get { return "201301262346346_CambioDataTypeFecha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
