// <auto-generated />
namespace RncManagement.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CargaInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CargaInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201301262302355_CargaInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
